-- MySQL Script generated by MySQL Workbench
-- mer. 19 juil. 2017 23:58:59 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `name` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organization` (
  `name` VARCHAR(45) NULL,
  `websiteurl` VARCHAR(45) NULL,
  `organizationid` INT NOT NULL,
  PRIMARY KEY (`organizationid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tweet` (
  `content` VARCHAR(45) NULL,
  `userid` INT NOT NULL,
  `idtweet` INT NOT NULL,
  INDEX `fk_tweet_user1_idx` (`userid` ASC),
  PRIMARY KEY (`idtweet`),
  CONSTRAINT `fk_tweet_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `mydb`.`user` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_organization` (
  `user_name` INT NOT NULL,
  `organization_name` INT NOT NULL,
  PRIMARY KEY (`user_name`, `organization_name`),
  INDEX `fk_user_has_organization_organization1_idx` (`organization_name` ASC),
  INDEX `fk_user_has_organization_user1_idx` (`user_name` ASC),
  CONSTRAINT `fk_user_has_organization_user1`
    FOREIGN KEY (`user_name`)
    REFERENCES `mydb`.`user` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_organization_organization1`
    FOREIGN KEY (`organization_name`)
    REFERENCES `mydb`.`organization` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
